
const K_PROFILE='msm_profile_v2_libras', K_ENTRIES='msm_entries_v2_libras';
const $=id=>document.getElementById(id);
const n=v=>{const x=Number(String(v||'').replace(',','.')); return Number.isFinite(x)?x:null};
const lbToKg=lb=>lb==null?null:lb*0.45359237;
const kgToLb=kg=>kg==null?null:kg/0.45359237;
function load(){return {profile:JSON.parse(localStorage.getItem(K_PROFILE)||'null'), entries:JSON.parse(localStorage.getItem(K_ENTRIES)||'[]')}}
function persist(p,e){localStorage.setItem(K_PROFILE,JSON.stringify(p));localStorage.setItem(K_ENTRIES,JSON.stringify(e));}
function age(b){if(!b)return null;let d=new Date(b),t=new Date(),a=t.getFullYear()-d.getFullYear(); if(t.getMonth()<d.getMonth()||(t.getMonth()==d.getMonth()&&t.getDate()<d.getDate()))a--; return a;}
function bmiFromLb(weightLb,heightCm){let kg=lbToKg(n(weightLb)),h=n(heightCm);return kg&&h?+(kg/((h/100)**2)).toFixed(1):null}
function weightLbOf(e){return Number(e.weightLb ?? kgToLb(e.weightKg) ?? 0)}
function score(profile, entries){if(!entries.length)return {health:0,risk:'Sin datos',trend:'Sin datos',recs:['Ingrese su primera medicion para iniciar.']}; const e=[...entries].sort((a,b)=>a.date.localeCompare(b.date)),last=e.at(-1),first=e[0],prev=e.length>1?e.at(-2):null; let s=100; if(last.bmi>=30)s-=22;else if(last.bmi>=25)s-=10; if(last.visceralFat>=15)s-=25;else if(last.visceralFat>=10)s-=12; const hf=profile.sex==='femenino'?32:25,mf=profile.sex==='femenino'?28:20,lm=profile.sex==='femenino'?25:32; if(last.bodyFatPct>hf)s-=18;else if(last.bodyFatPct>mf)s-=8; if(last.skeletalMusclePct<lm)s-=10;else s+=5; const ag=age(profile.birthDate); if(ag){const diff=last.bodyAge-ag; if(diff>8)s-=10;else if(diff>3)s-=4;else if(diff<=0)s+=6} const wdLb=weightLbOf(last)-weightLbOf(first),fd=last.bodyFatPct-first.bodyFatPct,md=last.skeletalMusclePct-first.skeletalMusclePct; if(fd<0&&md>=0)s+=6; if(wdLb<-3.3&&md<-.3)s-=6; s=Math.max(0,Math.min(100,Math.round(s))); let rp=0; if(last.bmi>=30)rp+=2;else if(last.bmi>=25)rp++; if(last.visceralFat>=15)rp+=2;else if(last.visceralFat>=10)rp++; if(last.bodyFatPct>hf)rp++; if(s<60)rp++; const risk=rp>=4?'Alto':rp>=2?'Moderado':'Bajo'; let rec=[]; if(prev){if(weightLbOf(last)-weightLbOf(prev)<-1.1 && last.skeletalMusclePct-prev.skeletalMusclePct<-.2)rec.push('Esta bajando peso, pero tambien musculo. Priorice fuerza y proteina suficiente.'); if(last.bodyFatPct-prev.bodyFatPct<0 && last.skeletalMusclePct-prev.skeletalMusclePct>=0)rec.push('Buen patron: la grasa baja y el musculo se mantiene o mejora.');} if(last.visceralFat>=10)rec.push('La grasa visceral esta en zona de seguimiento. Reduzca azucares liquidos, alcohol y ultraprocesados, y aumente caminatas o cardio moderado.'); if(last.bmi>=30)rec.push('El IMC esta en rango elevado. Busque una reduccion gradual y sostenible.'); if(ag&&last.bodyAge>ag)rec.push('La edad corporal esta por encima de su edad real. Enfoque el plan en recomposicion corporal, sueno y fuerza.'); if(last.sleepHours&&last.sleepHours<7)rec.push('El sueno registrado es menor a 7 horas. Mejorar descanso puede ayudar al control de apetito y recuperacion.'); if(!rec.length)rec.push('No hay alertas fuertes. Continue registrando para evaluar tendencias de 30 a 90 dias.'); rec.push('Estas recomendaciones son educativas y no sustituyen una evaluacion medica personalizada.'); return {health:s,risk,trend:(fd<0&&md>=0)?'Mejorando composicion':'En observacion',recs:rec,latest:last,wdLb,fd,md};}
function init(){let {profile}=load(); if(!profile){$('onboarding').classList.remove('hidden'); $('iDate').value=new Date().toISOString().slice(0,10);} else {$('app').classList.remove('hidden'); $('mDate').value=new Date().toISOString().slice(0,10); render();}}
function saveProfile(){const p={id:'local',name:$('pName').value.trim(),birthDate:$('pBirth').value,sex:$('pSex').value,heightCm:n($('pHeight').value)||0,targetWeightLb:n($('pTargetLb').value)||0,targetWeightKg:lbToKg(n($('pTargetLb').value)||0),activityLevel:$('pActivity').value,mainGoal:$('pGoal').value,waistCm:n($('pWaist').value),weightUnit:'lb',createdAt:new Date().toISOString()}; if(!p.name||!p.birthDate||!p.heightCm){alert('Complete nombre, fecha de nacimiento y altura.');return} let e=[]; if(n($('iWeightLb').value)){e.push(makeEntry('i','Medicion inicial'))} persist(p,e); location.reload();}
function makeEntry(prefix, notes=''){let d=$(prefix+'Date').value||new Date().toISOString().slice(0,10), wlb=n($(prefix+'WeightLb').value)||0; let {profile}=load(); let wkg=lbToKg(wlb)||0; return {id:Date.now().toString(),date:d,weightLb:wlb,weightKg:+wkg.toFixed(2),bodyFatPct:n($(prefix+'Fat').value)||0,skeletalMusclePct:n($(prefix+'Muscle').value)||0,bmi:n($(prefix+'Bmi').value)||bmiFromLb(wlb,profile?.heightCm)||0,visceralFat:n($(prefix+'Visceral').value)||0,basalMetabolism:n($(prefix+'Basal').value)||0,bodyAge:n($(prefix+'BodyAge').value)||0,sleepHours:n($('mSleep')?.value),systolic:n($('mSys')?.value),diastolic:n($('mDia')?.value),glucose:n($('mGlucose')?.value),notes:notes||$('mNotes')?.value||'',createdAt:new Date().toISOString()};}
function saveMeasurement(){let data=load(), item=makeEntry('m'); if(!item.weightLb||!item.bodyFatPct||!item.skeletalMusclePct){alert('Complete al menos peso en lb, grasa y musculo.');return} data.entries=data.entries.filter(x=>x.date!==item.date).concat(item).sort((a,b)=>a.date.localeCompare(b.date)); persist(data.profile,data.entries); ['WeightLb','Fat','Muscle','Bmi','Visceral','Basal','BodyAge'].forEach(k=>$('m'+k).value=''); $('mNotes').value=''; render(); showTab('dashboard',document.querySelector('.tab'));}
function render(){let {profile,entries}=load(), a=score(profile,entries); $('dashboard').innerHTML=`<div class="grid g4"><div class="card"><div class="muted">Health Score</div><div class="metric">${a.health}/100</div></div><div class="card"><div class="muted">Riesgo</div><div class="metric">${a.risk}</div></div><div class="card"><div class="muted">Ultimo peso</div><div class="metric">${a.latest?weightLbOf(a.latest).toFixed(1)+' lb':'-'}</div></div><div class="card"><div class="muted">Registros</div><div class="metric">${entries.length}</div></div></div><div class="card"><h2>Grafico de evolucion</h2><select id="metricSelect" onchange="drawChart(this.value)"><option value="weightLb">Peso lb</option><option value="bodyFatPct">Grasa %</option><option value="skeletalMusclePct">Musculo %</option><option value="bmi">IMC</option><option value="visceralFat">Grasa visceral</option><option value="bodyAge">Edad corporal</option></select><div class="chartBox"><canvas id="chart"></canvas></div></div><div class="card"><h2>Recomendaciones</h2>${a.recs.map(r=>`<div class="rec">${r}</div>`).join('')}</div>`; setTimeout(()=>drawChart('weightLb'),0); renderHistory(); renderProfile();}
function valForChart(e,key){return key==='weightLb'?weightLbOf(e):Number(e[key]||0)}
function drawChart(key){let {entries}=load(); const c=$('chart'); if(!c)return; const ctx=c.getContext('2d'), rect=c.parentElement.getBoundingClientRect(); c.width=rect.width*devicePixelRatio; c.height=rect.height*devicePixelRatio; ctx.scale(devicePixelRatio,devicePixelRatio); ctx.clearRect(0,0,rect.width,rect.height); const pad=40,w=rect.width-pad*2,h=rect.height-pad*2; ctx.strokeStyle='#e2e8f0'; ctx.lineWidth=1; ctx.strokeRect(pad,pad,w,h); if(entries.length<2){ctx.fillText('Agregue al menos dos mediciones para ver grafico.',pad+10,pad+30);return} entries=[...entries].sort((a,b)=>a.date.localeCompare(b.date)); const vals=entries.map(e=>valForChart(e,key)); const min=Math.min(...vals),max=Math.max(...vals),range=max-min||1; ctx.strokeStyle='#0ea5e9'; ctx.lineWidth=3; ctx.beginPath(); vals.forEach((v,i)=>{const x=pad+(i/(vals.length-1))*w,y=pad+h-((v-min)/range)*h; if(i)ctx.lineTo(x,y); else ctx.moveTo(x,y)}); ctx.stroke(); ctx.fillStyle='#0f172a'; ctx.font='12px system-ui'; ctx.fillText(max.toFixed(1),5,pad+5); ctx.fillText(min.toFixed(1),5,pad+h); entries.forEach((e,i)=>{if(i%Math.ceil(entries.length/4)===0)ctx.fillText(e.date.slice(5),pad+(i/(entries.length-1))*w-10,pad+h+20)});}
function renderHistory(){let {entries}=load(); $('historyBody').innerHTML=[...entries].reverse().map(e=>`<tr><td>${e.date}</td><td>${weightLbOf(e).toFixed(1)}</td><td>${(e.weightKg||lbToKg(weightLbOf(e))||0).toFixed(1)}</td><td>${e.bodyFatPct}</td><td>${e.skeletalMusclePct}</td><td>${e.bmi}</td><td>${e.visceralFat}</td><td>${e.basalMetabolism}</td><td>${e.bodyAge}</td><td><button class="danger" onclick="delEntry('${e.id}')">Borrar</button></td></tr>`).join('')}
function delEntry(id){let d=load(); d.entries=d.entries.filter(e=>e.id!==id); persist(d.profile,d.entries); render();}
function renderProfile(){let {profile:p}=load(); $('profileEdit').innerHTML=`<div class="grid g2"><div><label>Nombre</label><input id="eName" value="${p.name}"></div><div><label>Fecha nacimiento</label><input id="eBirth" type="date" value="${p.birthDate}"></div><div><label>Sexo</label><select id="eSex"><option ${p.sex==='masculino'?'selected':''} value="masculino">Masculino</option><option ${p.sex==='femenino'?'selected':''} value="femenino">Femenino</option></select></div><div><label>Altura cm</label><input id="eHeight" type="number" value="${p.heightCm}"></div><div><label>Peso objetivo lb</label><input id="eTargetLb" type="number" value="${p.targetWeightLb ?? (p.targetWeightKg?kgToLb(p.targetWeightKg).toFixed(1):'')}"></div></div>`}
function updateProfile(){let d=load(); d.profile={...d.profile,name:$('eName').value,birthDate:$('eBirth').value,sex:$('eSex').value,heightCm:n($('eHeight').value)||0,targetWeightLb:n($('eTargetLb').value)||0,targetWeightKg:lbToKg(n($('eTargetLb').value)||0),weightUnit:'lb',updatedAt:new Date().toISOString()}; persist(d.profile,d.entries); alert('Perfil actualizado'); render();}
function showTab(id,btn){document.querySelectorAll('.tabpage').forEach(x=>x.classList.add('hidden')); $(id).classList.remove('hidden'); document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active')); btn.classList.add('active'); if(id==='historial')renderHistory();}
function download(name,text,type){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function exportJSON(){let d=load(); download('backup_mi_salud_metabolica_libras_'+new Date().toISOString().slice(0,10)+'.json',JSON.stringify({...d,app:'Mi Salud Metabolica',version:2,weightUnit:'lb',exportedAt:new Date().toISOString()},null,2),'application/json')}
function exportCSV(){let {entries}=load(),h=['date','weightLb','weightKg','bodyFatPct','skeletalMusclePct','bmi','visceralFat','basalMetabolism','bodyAge','sleepHours','systolic','diastolic','glucose','notes']; let rows=[h.join(',')].concat(entries.map(e=>{let row={...e,weightLb:weightLbOf(e).toFixed(1),weightKg:(e.weightKg||lbToKg(weightLbOf(e))||0).toFixed(1)}; return h.map(k=>'"'+String(row[k]??'').replaceAll('"','""')+'"').join(',')})); download('historial_mi_salud_metabolica_libras.csv',rows.join('\n'),'text/csv')}
function importJSON(ev){let f=ev.target.files[0]; if(!f)return; let r=new FileReader(); r.onload=()=>{try{let d=JSON.parse(r.result); if(!d.profile||!Array.isArray(d.entries))throw 0; d.profile.weightUnit='lb'; d.entries=d.entries.map(e=>({...e,weightLb:weightLbOf(e),weightKg:e.weightKg||+(lbToKg(weightLbOf(e))||0).toFixed(2)})); persist(d.profile,d.entries); location.reload()}catch{alert('Archivo invalido')}}; r.readAsText(f)}
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})} init();
